services:
  webapi:
    build:
      context: .
      dockerfile: src/MovieDb.Api/Dockerfile
    container_name: webapi
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  mvc:
    build:
      context: .
      dockerfile: src/MovieDb.UI/Dockerfile
    container_name: mvc
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - webapi