version: '3.8'

services:
  webapi:
    build:
      context: ./MovieDb.Api
      dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  mvc:
    build:
      context: ./MovieDb.UI
      dockerfile: Dockerfile
    container_name: mvc
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - webapi